// flow-typed signature: d99b06029fe8e4d5713d5c7930cc1356
// flow-typed version: <<STUB>>/prompts_v2.2.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prompts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prompts' {
  declare module.exports: typeof prompts;
  declare var prompts: typeof npm$namespace$prompts;

  declare var npm$namespace$prompts: {|
    <T: string, R>(
      questions: prompts$PromptObject<T, R> | Array<prompts$PromptObject<T, R>>,
      options?: prompts$Options
    ): Promise<prompts$Answers<T>>,

    prompt: typeof prompts$prompt,

    inject: typeof npm$namespace$prompts$inject,
    prompts: typeof npm$namespace$prompts$prompts
  |};
  declare var prompts$prompt: any;

  declare var npm$namespace$prompts$inject: {|
    (obj: any): void,

    prototype: typeof prompts$inject$prototype
  |};
  declare var prompts$inject$prototype: { ... };

  declare var npm$namespace$prompts$prompts: {|
    autocomplete: typeof prompts$prompts$autocomplete,
    confirm: typeof prompts$prompts$confirm,
    date: typeof prompts$prompts$date,
    invisible: typeof prompts$prompts$invisible,
    list: typeof prompts$prompts$list,
    multiselect: typeof prompts$prompts$multiselect,
    number: typeof prompts$prompts$number,
    password: typeof prompts$prompts$password,
    select: typeof prompts$prompts$select,
    text: typeof prompts$prompts$text,
    toggle: typeof prompts$prompts$toggle
  |};
  declare function prompts$prompts$autocomplete(
    args: prompts$PromptObject<>
  ): any;

  declare function prompts$prompts$confirm(args: {
    message: string,
    initial?: boolean,
  }): Promise<boolean>;

  declare function prompts$prompts$date(args: prompts$PromptObject<>): any;

  declare function prompts$prompts$invisible(args: prompts$PromptObject<>): any;

  declare function prompts$prompts$list(args: prompts$PromptObject<>): any;

  declare function prompts$prompts$multiselect(
    args: prompts$PromptObject<>
  ): any;

  declare function prompts$prompts$number(args: prompts$PromptObject<>): void;

  declare function prompts$prompts$password(args: prompts$PromptObject<>): any;

  declare function prompts$prompts$select(args: prompts$PromptObject<>): void;

  declare function prompts$prompts$text(args: {
    message?: string,
    initial?: ?string,
    style?: 'default' | 'password' | 'invisible' | 'emoji',
  }): Promise<string>;

  declare function prompts$prompts$toggle(args: prompts$PromptObject<>): void;

  declare interface prompts$Choice {
    title: string;
    value: any;
    disable?: boolean;
  }

  declare interface prompts$Options {
    onSubmit?: (
      prompt: prompts$PromptObject<>,
      answer: any,
      answers: any[]
    ) => void;
    onCancel?: (prompt: prompts$PromptObject<>, answers: any) => void;
  }

  declare type prompts$PromptObject<T:string = string, R = string> = {
    type:
      | prompts$PromptType
      | prompts$Falsy
      | prompts$PrevCaller<T, prompts$PromptType | prompts$Falsy>;
    name: prompts$ValueOrFunc<string>;
    message?: string | prompts$PrevCaller<string>;
    initial?: string | number | boolean | Date;
    style?: string;
    format?: prompts$PrevCaller<T, R>;
    validate?: prompts$PrevCaller<T, boolean | string>;
    onState?: prompts$PrevCaller<T, void>;
    min?: number;
    max?: number;
    float?: boolean;
    round?: number;
    increment?: number;
    seperator?: string;
    active?: string;
    inactive?: string;
    choices?: prompts$Choice[];
    hint?: string;
    suggest?: (prev: any, values: any, prompt: prompts$PromptObject<>) => void;
    limit?: number;
    mask?: string;
    default?: string;
  }

  declare type prompts$Answers<T: string> = $ObjMapi<
    { [k: T]: any },
    <id>(id) => any
  >;

  declare type prompts$PrevCaller<T, R = T> = (
    prev: any,
    values: prompts$Answers<T>,
    prompt: prompts$PromptObject<>
  ) => R;

  declare type prompts$Falsy = false | null | void;

  declare type prompts$PromptType =
    | 'text'
    | 'password'
    | 'invisible'
    | 'number'
    | 'confirm'
    | 'list'
    | 'toggle'
    | 'select'
    | 'multiselect'
    | 'autocomplete'
    | 'date'
    | 'autocompleteMultiselect';

  declare type prompts$ValueOrFunc<T: string> = T | prompts$PrevCaller<T>;
}


/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prompts/dist/dateparts/datepart' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/day' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/hours' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/meridiem' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/milliseconds' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/minutes' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/month' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/seconds' {
  declare module.exports: any;
}

declare module 'prompts/dist/dateparts/year' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/autocomplete' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/autocompleteMultiselect' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/confirm' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/date' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/multiselect' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/number' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/prompt' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/select' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/text' {
  declare module.exports: any;
}

declare module 'prompts/dist/elements/toggle' {
  declare module.exports: any;
}

declare module 'prompts/dist' {
  declare module.exports: any;
}

declare module 'prompts/dist/prompts' {
  declare module.exports: any;
}

declare module 'prompts/dist/util/action' {
  declare module.exports: any;
}

declare module 'prompts/dist/util/clear' {
  declare module.exports: any;
}

declare module 'prompts/dist/util/figures' {
  declare module.exports: any;
}

declare module 'prompts/dist/util' {
  declare module.exports: any;
}

declare module 'prompts/dist/util/lines' {
  declare module.exports: any;
}

declare module 'prompts/dist/util/strip' {
  declare module.exports: any;
}

declare module 'prompts/dist/util/style' {
  declare module.exports: any;
}

declare module 'prompts/dist/util/wrap' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/datepart' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/day' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/hours' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/meridiem' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/milliseconds' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/minutes' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/month' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/seconds' {
  declare module.exports: any;
}

declare module 'prompts/lib/dateparts/year' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/autocomplete' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/autocompleteMultiselect' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/confirm' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/date' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/multiselect' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/number' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/prompt' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/select' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/text' {
  declare module.exports: any;
}

declare module 'prompts/lib/elements/toggle' {
  declare module.exports: any;
}

declare module 'prompts/lib' {
  declare module.exports: any;
}

declare module 'prompts/lib/prompts' {
  declare module.exports: any;
}

declare module 'prompts/lib/util/action' {
  declare module.exports: any;
}

declare module 'prompts/lib/util/clear' {
  declare module.exports: any;
}

declare module 'prompts/lib/util/figures' {
  declare module.exports: any;
}

declare module 'prompts/lib/util' {
  declare module.exports: any;
}

declare module 'prompts/lib/util/lines' {
  declare module.exports: any;
}

declare module 'prompts/lib/util/strip' {
  declare module.exports: any;
}

declare module 'prompts/lib/util/style' {
  declare module.exports: any;
}

declare module 'prompts/lib/util/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prompts/dist/dateparts/datepart.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/datepart'>;
}
declare module 'prompts/dist/dateparts/day.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/day'>;
}
declare module 'prompts/dist/dateparts/hours.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/hours'>;
}
declare module 'prompts/dist/dateparts/index' {
  declare module.exports: $Exports<'prompts/dist/dateparts'>;
}
declare module 'prompts/dist/dateparts/index.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts'>;
}
declare module 'prompts/dist/dateparts/meridiem.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/meridiem'>;
}
declare module 'prompts/dist/dateparts/milliseconds.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/milliseconds'>;
}
declare module 'prompts/dist/dateparts/minutes.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/minutes'>;
}
declare module 'prompts/dist/dateparts/month.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/month'>;
}
declare module 'prompts/dist/dateparts/seconds.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/seconds'>;
}
declare module 'prompts/dist/dateparts/year.js' {
  declare module.exports: $Exports<'prompts/dist/dateparts/year'>;
}
declare module 'prompts/dist/elements/autocomplete.js' {
  declare module.exports: $Exports<'prompts/dist/elements/autocomplete'>;
}
declare module 'prompts/dist/elements/autocompleteMultiselect.js' {
  declare module.exports: $Exports<'prompts/dist/elements/autocompleteMultiselect'>;
}
declare module 'prompts/dist/elements/confirm.js' {
  declare module.exports: $Exports<'prompts/dist/elements/confirm'>;
}
declare module 'prompts/dist/elements/date.js' {
  declare module.exports: $Exports<'prompts/dist/elements/date'>;
}
declare module 'prompts/dist/elements/index' {
  declare module.exports: $Exports<'prompts/dist/elements'>;
}
declare module 'prompts/dist/elements/index.js' {
  declare module.exports: $Exports<'prompts/dist/elements'>;
}
declare module 'prompts/dist/elements/multiselect.js' {
  declare module.exports: $Exports<'prompts/dist/elements/multiselect'>;
}
declare module 'prompts/dist/elements/number.js' {
  declare module.exports: $Exports<'prompts/dist/elements/number'>;
}
declare module 'prompts/dist/elements/prompt.js' {
  declare module.exports: $Exports<'prompts/dist/elements/prompt'>;
}
declare module 'prompts/dist/elements/select.js' {
  declare module.exports: $Exports<'prompts/dist/elements/select'>;
}
declare module 'prompts/dist/elements/text.js' {
  declare module.exports: $Exports<'prompts/dist/elements/text'>;
}
declare module 'prompts/dist/elements/toggle.js' {
  declare module.exports: $Exports<'prompts/dist/elements/toggle'>;
}
declare module 'prompts/dist/index' {
  declare module.exports: $Exports<'prompts/dist'>;
}
declare module 'prompts/dist/index.js' {
  declare module.exports: $Exports<'prompts/dist'>;
}
declare module 'prompts/dist/prompts.js' {
  declare module.exports: $Exports<'prompts/dist/prompts'>;
}
declare module 'prompts/dist/util/action.js' {
  declare module.exports: $Exports<'prompts/dist/util/action'>;
}
declare module 'prompts/dist/util/clear.js' {
  declare module.exports: $Exports<'prompts/dist/util/clear'>;
}
declare module 'prompts/dist/util/figures.js' {
  declare module.exports: $Exports<'prompts/dist/util/figures'>;
}
declare module 'prompts/dist/util/index' {
  declare module.exports: $Exports<'prompts/dist/util'>;
}
declare module 'prompts/dist/util/index.js' {
  declare module.exports: $Exports<'prompts/dist/util'>;
}
declare module 'prompts/dist/util/lines.js' {
  declare module.exports: $Exports<'prompts/dist/util/lines'>;
}
declare module 'prompts/dist/util/strip.js' {
  declare module.exports: $Exports<'prompts/dist/util/strip'>;
}
declare module 'prompts/dist/util/style.js' {
  declare module.exports: $Exports<'prompts/dist/util/style'>;
}
declare module 'prompts/dist/util/wrap.js' {
  declare module.exports: $Exports<'prompts/dist/util/wrap'>;
}
declare module 'prompts/index' {
  declare module.exports: $Exports<'prompts'>;
}
declare module 'prompts/index.js' {
  declare module.exports: $Exports<'prompts'>;
}
declare module 'prompts/lib/dateparts/datepart.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/datepart'>;
}
declare module 'prompts/lib/dateparts/day.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/day'>;
}
declare module 'prompts/lib/dateparts/hours.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/hours'>;
}
declare module 'prompts/lib/dateparts/index' {
  declare module.exports: $Exports<'prompts/lib/dateparts'>;
}
declare module 'prompts/lib/dateparts/index.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts'>;
}
declare module 'prompts/lib/dateparts/meridiem.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/meridiem'>;
}
declare module 'prompts/lib/dateparts/milliseconds.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/milliseconds'>;
}
declare module 'prompts/lib/dateparts/minutes.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/minutes'>;
}
declare module 'prompts/lib/dateparts/month.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/month'>;
}
declare module 'prompts/lib/dateparts/seconds.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/seconds'>;
}
declare module 'prompts/lib/dateparts/year.js' {
  declare module.exports: $Exports<'prompts/lib/dateparts/year'>;
}
declare module 'prompts/lib/elements/autocomplete.js' {
  declare module.exports: $Exports<'prompts/lib/elements/autocomplete'>;
}
declare module 'prompts/lib/elements/autocompleteMultiselect.js' {
  declare module.exports: $Exports<'prompts/lib/elements/autocompleteMultiselect'>;
}
declare module 'prompts/lib/elements/confirm.js' {
  declare module.exports: $Exports<'prompts/lib/elements/confirm'>;
}
declare module 'prompts/lib/elements/date.js' {
  declare module.exports: $Exports<'prompts/lib/elements/date'>;
}
declare module 'prompts/lib/elements/index' {
  declare module.exports: $Exports<'prompts/lib/elements'>;
}
declare module 'prompts/lib/elements/index.js' {
  declare module.exports: $Exports<'prompts/lib/elements'>;
}
declare module 'prompts/lib/elements/multiselect.js' {
  declare module.exports: $Exports<'prompts/lib/elements/multiselect'>;
}
declare module 'prompts/lib/elements/number.js' {
  declare module.exports: $Exports<'prompts/lib/elements/number'>;
}
declare module 'prompts/lib/elements/prompt.js' {
  declare module.exports: $Exports<'prompts/lib/elements/prompt'>;
}
declare module 'prompts/lib/elements/select.js' {
  declare module.exports: $Exports<'prompts/lib/elements/select'>;
}
declare module 'prompts/lib/elements/text.js' {
  declare module.exports: $Exports<'prompts/lib/elements/text'>;
}
declare module 'prompts/lib/elements/toggle.js' {
  declare module.exports: $Exports<'prompts/lib/elements/toggle'>;
}
declare module 'prompts/lib/index' {
  declare module.exports: $Exports<'prompts/lib'>;
}
declare module 'prompts/lib/index.js' {
  declare module.exports: $Exports<'prompts/lib'>;
}
declare module 'prompts/lib/prompts.js' {
  declare module.exports: $Exports<'prompts/lib/prompts'>;
}
declare module 'prompts/lib/util/action.js' {
  declare module.exports: $Exports<'prompts/lib/util/action'>;
}
declare module 'prompts/lib/util/clear.js' {
  declare module.exports: $Exports<'prompts/lib/util/clear'>;
}
declare module 'prompts/lib/util/figures.js' {
  declare module.exports: $Exports<'prompts/lib/util/figures'>;
}
declare module 'prompts/lib/util/index' {
  declare module.exports: $Exports<'prompts/lib/util'>;
}
declare module 'prompts/lib/util/index.js' {
  declare module.exports: $Exports<'prompts/lib/util'>;
}
declare module 'prompts/lib/util/lines.js' {
  declare module.exports: $Exports<'prompts/lib/util/lines'>;
}
declare module 'prompts/lib/util/strip.js' {
  declare module.exports: $Exports<'prompts/lib/util/strip'>;
}
declare module 'prompts/lib/util/style.js' {
  declare module.exports: $Exports<'prompts/lib/util/style'>;
}
declare module 'prompts/lib/util/wrap.js' {
  declare module.exports: $Exports<'prompts/lib/util/wrap'>;
}
