name: 'Setup'
description: 'Setup node, and install dependencies'

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "20.x"

    - name: Install dependencies
      shell: bash
      run: yarn
