name: Gerald - Notify on Push
'on':
  push:
    branches:
      - master
      - develop
      - main
jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ github.ref }}'
          fetch-depth: '$(node -e "console.log(${{ github.event.commits.length }}.length + 1")'
      - name: Run Gerald
        uses: Khan/gerald@main
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADMIN_PERMISSION_TOKEN: '${{ secrets.GERALD_SECRET }}'
          EVENT: 'push'