name: Gerald - Notify and Request Reviewers On Pull Request
'on':
 - pull_request
jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - uses: Khan/actions@gerald-pr-v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          admin-token: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}