name: Lint and Unit Test
'on':
  - pull_request

include:
  - _setup.yml

jobs:
  lint_and_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Run eslint
        uses: Khan/eslint-action@br
        setup: yarn
        with:
          eslint-lib: ./node_modules/eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run jest tests
        uses: Khan/jest-action@master
        setup: yarn
        with:
          jest-bin: ./node_modules/.bin/jest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If copying these actions from the OLC repo to your repo, you should probably delete the next three lines
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
          ATLASSIAN_API_USER: classroom-support@khanacademy.org
          ATLASSIAN_HOST: https://khanacademy.atlassian.net

      - name: Run jest coverage
        uses: Khan/jest-coverage-action@master
        setup: yarn
        with:
          jest-bin: ./node_modules/.bin/jest
          coverage-data-path: ./coverage/coverage-final.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flow
        uses: Khan/flow-action@master
        setup: yarn
        with:
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flow coverage
        uses: Khan/flow-coverage-action@master
        setup: yarn
        with:
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
