name: Build index.js
'on':
  push:
    branches:
      - main
      - debug
  pull_request:
    branches:
      - main
jobs:
  build_index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js, install deps
        uses: ./.github/actions/setup

      - name: Build dist folder
        run: pnpm run build

      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated build push" -a | exit 0

      - name: Push changes
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/debug'
        uses: ad-m/github-push-action@57116acb309081ee57864270b0e3c4cedbe45452 # master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
