name: Notify and Request Reviewers On Push
'on':
  push:
    branches:
      - master
      - develop
      - main
      - debug
jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.commits }}
      - uses: actions/checkout@v2
        with:
          ref: '${{ github.ref }}'
          fetch-depth: '${{ github.event.commits.length }}'
      - name: Run Gerald
        uses: Khan/gerald@debug
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADMIN_PERMISSION_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
          EVENT: 'push'