name: Notify and Request Reviewers On Push
'on':
  push:
    branches:
      - master
      - develop
      - main
      - debug
jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get fetch depth
        run: node ./getFetchDepth.js ${{ secrets.KHAN_ACITONS_BOT_TOKEN }}
      - run: git fetch
          with:
            ref: '${{ github.ref }}'
            fetch-depth:
      - name: Run Gerald
        uses: Khan/gerald@debug
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADMIN_PERMISSION_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
          EVENT: 'push'