name: Gerald - Check Comments
'on':
  issue_comment
jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - name: Run Gerald
        uses: Khan/gerald@5b4582365dafc568f0f67d29f7db637bd0c2ddf9 # main
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADMIN_PERMISSION_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
          EVENT: 'issue_comment'
