name: Gerald - Notify and Request Reviewers On Pull Request
'on':
  pull_request:
    # ready_for_review isn't included by default, so we add it
    # here to have this workflow re-run when a pr is converted
    # from "draft" to "not draft".
    # We also add "edited" to re-check when the base branch
    # is changed.
    types: [opened, synchronize, reopened, ready_for_review, edited]
# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  gerald:
    # Don't re-run if only the title or body changes
    if: github.event.action != 'edited' || github.event.changes.base != null
    runs-on: ubuntu-latest
    steps:
      - uses: Khan/gerald@e457f71e851d5ff1531331fcda0b9dad748efe6b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          admin-token: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}
