name: Gerald - Check Comments
'on':
  issue_comment
jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - name: Run Gerald
        uses: Khan/gerald@c8adc7c2ff208e7a0a76b48d660d00e406d17ee4 # main
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADMIN_PERMISSION_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
          EVENT: 'issue_comment'
