name: Gerald - Check Comments
'on':
  issue_comment
jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - name: Run Gerald
        uses: Khan/gerald@849ddb6db2db2ca094410b65a4e4a49d96ba7b06 # main
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          ADMIN_PERMISSION_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
          EVENT: 'issue_comment'
