name: Lint and Unit Test
'on':
  - pull_request

jobs:
  lint_and_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Node.js, install deps
        uses: ./.github/actions/setup

      - name: Run jest coverage
        run: pnpm test --coverage

      - name: Run flow
        run: pnpm flow
