name: Autofixers
on:
  - pull_request

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.actor != 'khan-actions-bot'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Node.js, install deps
        uses: ./.github/actions/setup

      - name: Get All Changed Files
        uses: Khan/actions@30cadf1146cce2e3cdd2510dc8378063e9b08b58 # get-changed-files-v3
        id: changed
        with:
          directories: src/

      - id: changed-js
        name: Find .js changed files
        uses: Khan/actions@069171ef7dea82ab80a8e499c4217d9b812f6af4 # filter-files-v3
        if: always()
        with:
          changed-files: ${{ steps.changed.outputs.files }}
          extensions: '.js'

      - name: Run prettier
        if: steps.changed-js.outputs.filtered != '[]'
        run: echo '${{ steps.changed-js.outputs.filtered }}' | jq -r .[] | xargs pnpm run format-files

      - name: Rebuild our "dist" file
        if: steps.changed.outputs.files != '[]'
        run: pnpm build

      - uses: Khan/autofix-commit-action@259499a361ea28f5d93f44b12b5cf0dee9a7b6b4 # main
        env:
          GITHUB_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
