name: Lint and Unit Test
on:
  - pull_request

jobs:
  lint_and_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js, install deps
        uses: ./.github/actions/setup

      - name: Run jest coverage
        uses: Khan/jest-coverage-action@master
        with:
          jest-bin: ./node_modules/.bin/jest
          coverage-data-path: ./coverage/coverage-final.json
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Run flow
        uses: Khan/flow-action@master
        with:
          flow-bin: ./node_modules/.bin/flow
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
