name: Autofixers
on:
  - pull_request

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.actor != 'khan-actions-bot'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js, install deps
        uses: ./.github/actions/setup

      - name: Get All Changed Files
        uses: Khan/actions@1662367b281368328845c72f77028f71d768b588 # get-changed-files-v2
        id: changed
        with:
          directories: src/

      - id: changed-js
        name: Find .js changed files
        uses: Khan/actions@70e6afa0077187462838d024a1773adf217fb2b8 # filter-files-v2
        if: always()
        with:
          changed-files: ${{ steps.changed.outputs.files }}
          extensions: '.js'

      - name: Run prettier
        if: steps.changed-js.outputs.filtered != '[]'
        run: echo '${{ steps.changed-js.outputs.filtered }}' | jq -r .[] | xargs yarn run format-files

      - name: Rebuild our "dist" file
        if: steps.changed.outputs.files != '[]'
        run: yarn build

      - uses: Khan/autofix-commit-action@7ad29653a245c4bc54859d8644f233f94a99a183 # main
        env:
          GITHUB_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
