name: Autofixers
on:
  - pull_request

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.actor != 'khan-actions-bot'
    steps:
      - name: "\U0001F53D Start setup [checkout]"
        uses: ./.github/actions/checkout

      - id: paths_src_
        name: 'Check paths: src/**'
        run: >-
          BASE=${GITHUB_BASE_REF:-HEAD~1}

          if [[ -n $(git diff --name-only refs/remotes/origin/$BASE --relative |
          grep '^src/.*$') ]]

          then

          echo "::set-output name=changed::true"

          exit 0

          fi

          echo "::set-output name=changed::false"

          exit 0

      - name: Run prettier
        run: >-
          node ./node_modules/actions-utils/list-changed-files.js | grep
          '.*\.js$' | xargs npm run -s format-files

      - name: Rebuild our "dist" file
        run: yarn build
        if: steps.paths_src_.outputs.changed == 'true'

      - uses: Khan/autofix-commit-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}'
