name: Lint and Unit Test
'on':
  - pull_request

jobs:
  lint_and_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js, install deps
        uses: ./.github/actions/setup

      - name: Run jest coverage
        run: yarn test --coverage

      - name: Run flow
        run: yarn flow
